### ISSUE TITLE
undefined property 'media' and 'sort' 

### ISSUE THREAD

**Issue by chuckreynolds** [chiefsmurph/johns-instabot#4]
```
starting
initd 0 docs in handles collection
logging in...
opened login page
finished typing now submitting!
getting recent photos for tag: machinelearning
done getting photos for tag machinelearning
length photos 15
url:  https://www.instagram.com/p/Bkmd-f3hxWH/?tagged=machinelearning
done getting username of https://www.instagram.com/p/Bkmd-f3hxWH/?tagged=machinelearning
getting data of  _develop_app
url:  https://www.instagram.com/_develop_app
Error: Evaluation failed: TypeError: Cannot read property 'media' of undefined
    at <anonymous>:1:58
    at ExecutionContext.evaluateHandle (/Users/chuck/Sites/dev/bots/johns-instabot/node_modules/puppeteer/lib/ExecutionContext.js:66:13)
    at process._tickCallback (internal/process/next_tick.js:68:7) '_develop_app'
done getting data of _develop_app
get photos and schedule likes error TypeError: Cannot read property 'sort' of undefined
    at getPhotosAndScheduleLikes (/Users/chuck/Sites/dev/bots/johns-instabot/actions/multiple/getPhotosAndScheduleLikes.js:111:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
going to schedule more pic likes in: 1.6 min
```

**Comment by chiefsmurph** [comment]
this should be fixed as well.  looks like instagram may have changed things to make it difficult to scrape a users' photos from the console.
